version: "3.7"

services:

  wanda:
    image: ghcr.io/trento-project/trento-wanda:rolling
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/postgres
      SECRET_KEY_BASE: dummyS3cr3t
      AMQP_URL: amqp://wanda:wanda@rabbitmq
      CORS_ENABLED: "false"
      CATALOG_PATH: /app/catalog
      JWT_AUTHENTICATION_ENABLED: "false"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 4000:4000
    entrypoint: /bin/sh -c "/app/bin/wanda eval \"Wanda.Release.init()\" && /app/bin/wanda start"
    volumes:
      - ./checks:/usr/share/trento/checks:ro

  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: rabbitmq-diagnostics -q status
        interval: 30s
        timeout: 30s
        retries: 10
    environment:
      RABBITMQ_DEFAULT_USER: wanda
      RABBITMQ_DEFAULT_PASS: wanda

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 10s
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:

